version: "3.5"

services:
  jekyll:
    image: albion-data-website
    build:
      context: ./
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -l
    